language: android
android:
  components:
  # Uncomment the lines below if you want to
  # use the latest revision of Android SDK Tools
    - tools
    - platform-tools
    - android-29
    - build-tools-29.0.3

env:
  global:
    # install timeout in minutes (2 minutes by default)
    - ADB_INSTALL_TIMEOUT=8

# Run assemble and unit tests
script:
  - echo $KEYSTOREPROPERTIES > keystore.properties
  - ls -l
  - echo $KEYSTORE | base64 -d > app/ngx-release-key.keystore
  - mkdir app/src/debug
  - mkdir app/src/release
  - echo $GSERVICE_DEBUG > app/src/debug/google-services.json
  - echo $GSERVICE_RELEASE  > app/src/release/google-services.json
  - export GRADLE_USER_HOME=$(pwd)/.gradle
  - chmod +x ./gradlew
  #- ./gradlew clean assembleDebug testDebug assembleRelease
  - ./gradlew clean --debug
  - ./gradlew assembleRelease --info
  - rm -f keystore.properties
  - rm -f app/ngx-release-key.keystore
  - rm -rf app/src/debug
  - rm -rf app/src/release
