language: android
android:
  components:
    - android-28
    - build-tools-27.0.3

env:
  global:
    # install timeout in minutes (2 minutes by default)
    - ADB_INSTALL_TIMEOUT=8

# Run assemble and unit tests
script:
  - echo $KEYSTOREPROPERTIES | base64 -d > keystore.properties
  - echo $KEYSTORE | base64 -d > app/ngx-release-key.keystore
  - mkdir app/src/debug
  - mkdir app/src/release
  - echo $GSERVICE_DEBUG  | base64 -d > app/src/debug/google-services.json
  - echo GSERVICE_RELEASE | base64 -d > app/src/release/google-services.json
  - ./gradlew clean assembleDebug testDebug assembleRelease
  - rm -f keystore.properties
  - rm -f app/ngx-release-key.keystore
  - rm -rf app/src/debug
  - rm -rf app/src/release